version: "3.9"
services:
  nextjs:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    restart: always

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"

    restart: always
