version: '3'

services:
  nextjs:
    build:
      context: ./frontend  # ระบุ path ของ frontend ที่มี Dockerfile
      dockerfile: Dockerfile
    container_name: nextjs-app
    ports:
      - "3000:3000" # หรือใช้ port ที่คุณต้องการ
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    command: ["npm", "run", "start"] # คำสั่งในการ run Next.js ใน production mode

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/public:/usr/share/nginx/html
    networks:
      - app-network
    depends_on:
      - nextjs

networks:
  app-network:
    driver: bridge
