FROM nginx:alpine
COPY ./default.conf /etc/nginx/conf.d/default.conf
COPY ./frontend/.next /srv/app/frontend/.next  # Copy โฟลเดอร์ .next
COPY ./frontend/public /srv/app/frontend/public  # Copy โฟลเดอร์ public

    

